# Generated by Django 5.2.4 on 2026-01-18 15:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channal',
            new_name='Channel',
        ),
        migrations.RenameModel(
            old_name='ChannalMessage',
            new_name='ChannelMessage',
        ),
    ]
