# Generated by Django 6.0.1 on 2026-01-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/channel/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/group/'),
        ),
    ]
