# Generated by Django 5.2.4 on 2026-01-18 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_channal_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmessage',
            name='group',
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.channel'),
        ),
    ]
