# Generated by Django 5.2.4 on 2026-01-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_channelmessagecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='shared_media',
            field=models.ImageField(blank=True, null=True, upload_to='shared_media/channel/'),
        ),
    ]
