# Generated by Django 5.2.4 on 2026-01-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_channelmessage_shared_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessagecomment',
            name='shared_media',
            field=models.ImageField(blank=True, null=True, upload_to='shared_media/comments/'),
        ),
        migrations.AddField(
            model_name='friendmessage',
            name='shared_media',
            field=models.ImageField(blank=True, null=True, upload_to='shared_media/friend/'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='shared_media',
            field=models.ImageField(blank=True, null=True, upload_to='shared_media/group/'),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
